In [21]:
import numpy as np
import pandas as pd
scores = np.random.randint(50,101,size=(50,5))
scores_pd = pd.DataFrame(scores,
             columns=['國文', '英文', '數學', '地理', '歷史'],
             index = range(1,51)
             )
scores_pd

    國文   英文   數學  地理  歷史
1   67   78   93  51  97
2   57   59   57  74  86
3   98   52   74  89  77
4   75   62   54  97  87
5   68   82   59  79  54
6   51   98   81  68  68
7   71   89   64  87  98
8   50   62   87  87  93
9   56   66   63  87  80
10  90   70   94  99  99
11  58   55   61  70  97
12  65   58   97  72  65
13  52   67   75  91  55
14  71   59   87  69  77
15  55   65   61  63  81
16  99   77   67  95  86
17  61   97   63  76  51
18  77   85   61  85  60
19  82   97   87  72  68
20  84   67   97  84  88
21  63   63   91  80  60
22  76   81   57  74  55
23  53   63   95  76  78
24  96   77   83  86  63
25  64   92   77  96  89
26  81   76   54  94  80
27  74   71   84  55  95
28  70   76   70  67  82
29  58   96   98  55  63
30  66   86   69  79  74
31  52   71   93  78  67
32  60   54   77  54  71
33  81   60   60  80  80
34  72  100   74  57  68
35  63   60   53  88  59
36  92   67   68  78  52
37  61   53   65  94  58
38  90   76   68  82  58
39  62   88   83  57  88
40  99   76   74  63  55
41  73   97   85  69  51
42  65   99  100  89  56
43  73   61   63  59  96
44  77   54   73  88  86
45  71   89   90  50  87
46  97   72   71  67  95
47  81   86   97  60  50
48  68   54   97  92  50
49  55   89   63  78  67
50  69   63   73  51  71

In [22]:
scores_pd.index.name="學號"
scores_pd.columns.name="科目"
scores_pd

科目  國文   英文   數學  地理  歷史
學號
1   67   78   93  51  97
2   57   59   57  74  86
3   98   52   74  89  77
4   75   62   54  97  87
5   68   82   59  79  54
6   51   98   81  68  68
7   71   89   64  87  98
8   50   62   87  87  93
9   56   66   63  87  80
10  90   70   94  99  99
11  58   55   61  70  97
12  65   58   97  72  65
13  52   67   75  91  55
14  71   59   87  69  77
15  55   65   61  63  81
16  99   77   67  95  86
17  61   97   63  76  51
18  77   85   61  85  60
19  82   97   87  72  68
20  84   67   97  84  88
21  63   63   91  80  60
22  76   81   57  74  55
23  53   63   95  76  78
24  96   77   83  86  63
25  64   92   77  96  89
26  81   76   54  94  80
27  74   71   84  55  95
28  70   76   70  67  82
29  58   96   98  55  63
30  66   86   69  79  74
31  52   71   93  78  67
32  60   54   77  54  71
33  81   60   60  80  80
34  72  100   74  57  68
35  63   60   53  88  59
36  92   67   68  78  52
37  61   53   65  94  58
38  90   76   68  82  58
39  62   88   83  57  88
40  99   76   74  63  55
41  73   97   85  69  51
42  65   99  100  89  56
43  73   61   63  59  96
44  77   54   73  88  86
45  71   89   90  50  87
46  97   72   71  67  95
47  81   86   97  60  50
48  68   54   97  92  50
49  55   89   63  78  67
50  69   63   73  51  71

In [23]:
display(scores_pd['國文'][:10])
scores_pd['數學'][:10]
scores_pd.info()

學號
1     67
2     57
3     98
4     75
5     68
6     51
7     71
8     50
9     56
10    90
Name: 國文, dtype: int32

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 1 to 50
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   國文      50 non-null     int32
 1   英文      50 non-null     int32
 2   數學      50 non-null     int32
 3   地理      50 non-null     int32
 4   歷史      50 non-null     int32
dtypes: int32(5)
memory usage: 1.1 KB

In [24]:
scores_pd['國文'][:10] + scores_pd['數學'][:10]

學號
1     160
2     114
3     172
4     129
5     127
6     132
7     135
8     137
9     119
10    184
dtype: int32

In [25]:
scores_pd['國文'] + scores_pd['英文'] + scores_pd['地理'] + scores_pd['歷史'] + scores_pd['數學']

學號
1     386
2     333
3     390
4     375
5     342
6     366
7     409
8     379
9     352
10    452
11    341
12    357
13    340
14    363
15    325
16    424
17    348
18    368
19    406
20    420
21    357
22    343
23    365
24    405
25    418
26    385
27    379
28    365
29    370
30    374
31    361
32    316
33    361
34    371
35    323
36    357
37    331
38    374
39    378
40    367
41    375
42    409
43    352
44    378
45    387
46    402
47    374
48    361
49    352
50    327
dtype: int32

In [26]:
#統計的實體方法,sum()
scores_pd['總分'] = scores_pd[['國文','英文','數學','地理','歷史']].sum(axis=1)
scores_pd
scores_pd['平均'] = scores_pd[['國文','英文','數學','地理','歷史']].mean(axis=1)
scores_pd

科目  國文   英文   數學  地理  歷史   總分    平均
學號
1   67   78   93  51  97  386  77.2
2   57   59   57  74  86  333  66.6
3   98   52   74  89  77  390  78.0
4   75   62   54  97  87  375  75.0
5   68   82   59  79  54  342  68.4
6   51   98   81  68  68  366  73.2
7   71   89   64  87  98  409  81.8
8   50   62   87  87  93  379  75.8
9   56   66   63  87  80  352  70.4
10  90   70   94  99  99  452  90.4
11  58   55   61  70  97  341  68.2
12  65   58   97  72  65  357  71.4
13  52   67   75  91  55  340  68.0
14  71   59   87  69  77  363  72.6
15  55   65   61  63  81  325  65.0
16  99   77   67  95  86  424  84.8
17  61   97   63  76  51  348  69.6
18  77   85   61  85  60  368  73.6
19  82   97   87  72  68  406  81.2
20  84   67   97  84  88  420  84.0
21  63   63   91  80  60  357  71.4
22  76   81   57  74  55  343  68.6
23  53   63   95  76  78  365  73.0
24  96   77   83  86  63  405  81.0
25  64   92   77  96  89  418  83.6
26  81   76   54  94  80  385  77.0
27  74   71   84  55  95  379  75.8
28  70   76   70  67  82  365  73.0
29  58   96   98  55  63  370  74.0
30  66   86   69  79  74  374  74.8
31  52   71   93  78  67  361  72.2
32  60   54   77  54  71  316  63.2
33  81   60   60  80  80  361  72.2
34  72  100   74  57  68  371  74.2
35  63   60   53  88  59  323  64.6
36  92   67   68  78  52  357  71.4
37  61   53   65  94  58  331  66.2
38  90   76   68  82  58  374  74.8
39  62   88   83  57  88  378  75.6
40  99   76   74  63  55  367  73.4
41  73   97   85  69  51  375  75.0
42  65   99  100  89  56  409  81.8
43  73   61   63  59  96  352  70.4
44  77   54   73  88  86  378  75.6
45  71   89   90  50  87  387  77.4
46  97   72   71  67  95  402  80.4
47  81   86   97  60  50  374  74.8
48  68   54   97  92  50  361  72.2
49  55   89   63  78  67  352  70.4
50  69   63   73  51  71  327  65.4

In [27]:
scores_pd['排名'] = scores_pd['總分'].rank(method='min',ascending=False)
scores_pd

科目  國文   英文   數學  地理  歷史   總分    平均    排名
學號
1   67   78   93  51  97  386  77.2  12.0
2   57   59   57  74  86  333  66.6  45.0
3   98   52   74  89  77  390  78.0  10.0
4   75   62   54  97  87  375  75.0  18.0
5   68   82   59  79  54  342  68.4  42.0
6   51   98   81  68  68  366  73.2  27.0
7   71   89   64  87  98  409  81.8   5.0
8   50   62   87  87  93  379  75.8  14.0
9   56   66   63  87  80  352  70.4  37.0
10  90   70   94  99  99  452  90.4   1.0
11  58   55   61  70  97  341  68.2  43.0
12  65   58   97  72  65  357  71.4  34.0
13  52   67   75  91  55  340  68.0  44.0
14  71   59   87  69  77  363  72.6  30.0
15  55   65   61  63  81  325  65.0  48.0
16  99   77   67  95  86  424  84.8   2.0
17  61   97   63  76  51  348  69.6  40.0
18  77   85   61  85  60  368  73.6  25.0
19  82   97   87  72  68  406  81.2   7.0
20  84   67   97  84  88  420  84.0   3.0
21  63   63   91  80  60  357  71.4  34.0
22  76   81   57  74  55  343  68.6  41.0
23  53   63   95  76  78  365  73.0  28.0
24  96   77   83  86  63  405  81.0   8.0
25  64   92   77  96  89  418  83.6   4.0
26  81   76   54  94  80  385  77.0  13.0
27  74   71   84  55  95  379  75.8  14.0
28  70   76   70  67  82  365  73.0  28.0
29  58   96   98  55  63  370  74.0  24.0
30  66   86   69  79  74  374  74.8  20.0
31  52   71   93  78  67  361  72.2  31.0
32  60   54   77  54  71  316  63.2  50.0
33  81   60   60  80  80  361  72.2  31.0
34  72  100   74  57  68  371  74.2  23.0
35  63   60   53  88  59  323  64.6  49.0
36  92   67   68  78  52  357  71.4  34.0
37  61   53   65  94  58  331  66.2  46.0
38  90   76   68  82  58  374  74.8  20.0
39  62   88   83  57  88  378  75.6  16.0
40  99   76   74  63  55  367  73.4  26.0
41  73   97   85  69  51  375  75.0  18.0
42  65   99  100  89  56  409  81.8   5.0
43  73   61   63  59  96  352  70.4  37.0
44  77   54   73  88  86  378  75.6  16.0
45  71   89   90  50  87  387  77.4  11.0
46  97   72   71  67  95  402  80.4   9.0
47  81   86   97  60  50  374  74.8  20.0
48  68   54   97  92  50  361  72.2  31.0
49  55   89   63  78  67  352  70.4  37.0
50  69   63   73  51  71  327  65.4  47.0

In [28]:
scores_pd.sort_values(by='排名')

科目  國文   英文   數學  地理  歷史   總分    平均    排名
學號
10  90   70   94  99  99  452  90.4   1.0
16  99   77   67  95  86  424  84.8   2.0
20  84   67   97  84  88  420  84.0   3.0
25  64   92   77  96  89  418  83.6   4.0
42  65   99  100  89  56  409  81.8   5.0
7   71   89   64  87  98  409  81.8   5.0
19  82   97   87  72  68  406  81.2   7.0
24  96   77   83  86  63  405  81.0   8.0
46  97   72   71  67  95  402  80.4   9.0
3   98   52   74  89  77  390  78.0  10.0
45  71   89   90  50  87  387  77.4  11.0
1   67   78   93  51  97  386  77.2  12.0
26  81   76   54  94  80  385  77.0  13.0
27  74   71   84  55  95  379  75.8  14.0
8   50   62   87  87  93  379  75.8  14.0
39  62   88   83  57  88  378  75.6  16.0
44  77   54   73  88  86  378  75.6  16.0
4   75   62   54  97  87  375  75.0  18.0
41  73   97   85  69  51  375  75.0  18.0
30  66   86   69  79  74  374  74.8  20.0
47  81   86   97  60  50  374  74.8  20.0
38  90   76   68  82  58  374  74.8  20.0
34  72  100   74  57  68  371  74.2  23.0
29  58   96   98  55  63  370  74.0  24.0
18  77   85   61  85  60  368  73.6  25.0
40  99   76   74  63  55  367  73.4  26.0
6   51   98   81  68  68  366  73.2  27.0
23  53   63   95  76  78  365  73.0  28.0
28  70   76   70  67  82  365  73.0  28.0
14  71   59   87  69  77  363  72.6  30.0
33  81   60   60  80  80  361  72.2  31.0
31  52   71   93  78  67  361  72.2  31.0
48  68   54   97  92  50  361  72.2  31.0
36  92   67   68  78  52  357  71.4  34.0
21  63   63   91  80  60  357  71.4  34.0
12  65   58   97  72  65  357  71.4  34.0
49  55   89   63  78  67  352  70.4  37.0
9   56   66   63  87  80  352  70.4  37.0
43  73   61   63  59  96  352  70.4  37.0
17  61   97   63  76  51  348  69.6  40.0
22  76   81   57  74  55  343  68.6  41.0
5   68   82   59  79  54  342  68.4  42.0
11  58   55   61  70  97  341  68.2  43.0
13  52   67   75  91  55  340  68.0  44.0
2   57   59   57  74  86  333  66.6  45.0
37  61   53   65  94  58  331  66.2  46.0
50  69   63   73  51  71  327  65.4  47.0
15  55   65   61  63  81  325  65.0  48.0
35  63   60   53  88  59  323  64.6  49.0
32  60   54   77  54  71  316  63.2  50.0

In [29]:
def format60(v:int):
    if v >= 60:
        return '及格'
    else:
        return '不及格'

scores_pd[['國文','英文','數學','地理','歷史']].style.format(format60)

In [30]:
scores_pd.style.highlight_between(left=0,
                                  right=59,
                                  color='red',
                                  subset=['國文','英文','數學','地理','歷史'])

In [31]:
scores_pd.style\
.highlight_between(left=0,
                   right=59,
                   color='red',
                   subset=['國文','英文','數學','地理','歷史'],
                   props='color:white;background-color:red')\
.format(precision=0,subset=['平均','排名'])

In [ ]:
scores_pd.style\
.highlight_between(left=0,
                   right=59,
                   color='red',
                   subset=['國文','英文','數學','地理','歷史'],
                   props='color:white;background-color:red')\
.format(precision=0,subset=['平均','排名']).to_excel('scores.xlsx')